utilisateur:
    pattern:  /
    defaults: { _controller: "AngeAngeBundle:Utilisateur:index" }

utilisateur_show:
    pattern:  /{id}/show
    defaults: { _controller: "AngeAngeBundle:Utilisateur:show" }

utilisateur_new:
    pattern:  /new
    defaults: { _controller: "AngeAngeBundle:Utilisateur:new" }

utilisateur_create:
    pattern:  /create
    defaults: { _controller: "AngeAngeBundle:Utilisateur:create" }
    requirements: { _method: post }

utilisateur_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AngeAngeBundle:Utilisateur:edit" }

utilisateur_update:
    pattern:  /{id}/update
    defaults: { _controller: "AngeAngeBundle:Utilisateur:update" }
    requirements: { _method: post }

utilisateur_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AngeAngeBundle:Utilisateur:delete" }
    requirements: { _method: post }
