Matiere:
  type: entity
  table: matiere
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    label:
      type: string
      length: 100
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
