AngeAngeBundle_home:
    pattern:  /
    defaults: { _controller: "AngeAngeBundle:Home:index" }
    
AngeAngeBundle_cours:
    resource: "routing/cours.yml"
    prefix:   /cours
    
AngeAngeBundle_devoir:
    resource: "routing/devoir.yml"
    prefix:   /devoir

AngeAngeBundle_groupe:
    resource: "routing/groupe.yml"
    prefix:   /groupe
    
AngeAngeBundle_groupedevoir:
    resource: "routing/groupedevoir.yml"
    prefix:   /groupedevoir
    
AngeAngeBundle_matiere:
    resource: "routing/matiere.yml"
    prefix:   /matiere

AngeAngeBundle_note:
    resource: "routing/note.yml"
    prefix:   /note

AngeAngeBundle_promotion:
    resource: "routing/promotion.yml"
    prefix:   /promotion
    
AngeAngeBundle_salle:
    resource: "routing/salle.yml"
    prefix:   /salle

AngeAngeBundle_utilisateur:
    resource: "routing/utilisateur.yml"
    prefix:   /utilisateur

AngeAngeBundle_utilisateurcours:
    resource: "routing/utilisateurcours.yml"
    prefix:   /utilisateurcours
        
AngeAngeBundle_contenu:
    resource: "routing/contenu.yml"
    prefix:   /contenu
    
home_etu:
    pattern: /etu
    defaults: { _controller: "AngeAngeBundle:Home:indexEtu" }

home_prof:
    pattern: /prof
    defaults: { _controller: "AngeAngeBundle:Home:indexProf" }

home_admin:
    pattern: /admin
    defaults: { _controller: "AngeAngeBundle:Home:indexAdmin" }
            
note_etu:
    pattern: /etu/note
    defaults: { _controller: "AngeAngeBundle:Note:noteEtudiant" }

note_prof:
    pattern: /prof/note
    defaults: { _controller: "AngeAngeBundle:Note:noteProf" }
    
note_admin:
    pattern: /admin/note
    defaults: { _controller: "AngeAngeBundle:Note:noteAdmin" }
        
profil:
    pattern: /consulterProfil
    defaults: { _controller: "AngeAngeBundle:Utilisateur:consulter" }

contact:
    pattern: /contact
    defaults: { _controller: "AngeAngeBundle:Utilisateur:contact" }
    
utilisateur_envoi_mail:   
    pattern: /utilisateurEnvoiMail
    defaults: { _controller: "AngeAngeBundle:Utilisateur:envoiMail" }
    
feuille_presence_prof:
    pattern: /prof/{id}/feuillePresenceProf
    defaults: { _controller: "AngeAngeBundle:UtilisateurCours:feuilleDePresence" }
    
remplir_feuille:
    pattern: /prof/{id}/remplirFeuille
    defaults: { _controller: "AngeAngeBundle:UtilisateurCours:remplirFeuille" }
    
devoir_etu:
    pattern: /etu/devoir
    defaults: { _controller: "AngeAngeBundle:Devoir:devoirEtudiant" }
    
absence_etu:
    pattern: /etu/absence
    defaults: { _controller: "AngeAngeBundle:UtilisateurCours:absenceEtudiant" }
    
absence_prof:
    pattern: /prof/absence
    defaults: { _controller: "AngeAngeBundle:UtilisateurCours:absenceProf" }
    
absence_admin:
    pattern: /admin/absence
    defaults: { _controller: "AngeAngeBundle:UtilisateurCours:absenceAdmin" }