<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AngeAngeBundleEntityCoursProxy extends \Ange\AngeBundle\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setLabel($label)
    {
        $this->__load();
        return parent::setLabel($label);
    }

    public function getLabel()
    {
        $this->__load();
        return parent::getLabel();
    }

    public function setIdMatiere(\Ange\AngeBundle\Entity\Matiere $idMatiere)
    {
        $this->__load();
        return parent::setIdMatiere($idMatiere);
    }

    public function getIdMatiere()
    {
        $this->__load();
        return parent::getIdMatiere();
    }

    public function setIdSalle(\Ange\AngeBundle\Entity\Salle $idSalle)
    {
        $this->__load();
        return parent::setIdSalle($idSalle);
    }

    public function getIdSalle()
    {
        $this->__load();
        return parent::getIdSalle();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function isAnneeCourante()
    {
        $this->__load();
        return parent::isAnneeCourante();
    }

    public function isPasse()
    {
        $this->__load();
        return parent::isPasse();
    }

    public function isPasseAnneeCourante()
    {
        $this->__load();
        return parent::isPasseAnneeCourante();
    }

    public function isAVenir()
    {
        $this->__load();
        return parent::isAVenir();
    }

    public function isAVenirAnneeCourante()
    {
        $this->__load();
        return parent::isAVenirAnneeCourante();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'label', 'date', 'idMatiere', 'idSalle');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}